require 'Magento.rb'
require 'MagentoMappingRegistry.rb'
require 'soap/rpc/driver'

class Mage_Api_Model_Server_Wsi_HandlerPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://localdev-admin.compperformance.com/index.php/api/v2_soap/index/?SID=hmp7b6e13mcaokbgaopo4pk8u1"

  Methods = [
    [ "",
      "call",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "callParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "callResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "multiCall",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "multiCallParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "multiCallResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "endSession",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "endSessionParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "endSessionResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "login",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "loginParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "loginResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "startSession",
      [ [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "startSessionResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "resources",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "resourcesRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "resourcesResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "globalFaults",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "globalFaultsParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "globalFaultsResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "resourceFaults",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "resourceFaultsParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "resourceFaultsResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "storeList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "storeListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "storeListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "storeInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "storeInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "storeInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "magentoInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "magentoInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "magentoInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "directoryCountryList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "directoryCountryListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "directoryCountryListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "directoryRegionList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "directoryRegionListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "directoryRegionListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerCustomerList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerCustomerCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerCustomerInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerCustomerUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerCustomerDelete",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerDeleteRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerCustomerDeleteResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerGroupList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerGroupListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerGroupListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerAddressList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerAddressCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerAddressInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerAddressUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "customerAddressDelete",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressDeleteRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "customerAddressDeleteResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryCurrentStore",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryCurrentStoreRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryCurrentStoreResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryTree",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryTreeRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryTreeResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryLevel",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryLevelRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryLevelResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryMove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryMoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryMoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryDelete",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryDeleteRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryDeleteResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryAssignedProducts",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAssignedProductsRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAssignedProductsResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryAssignProduct",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAssignProductRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAssignProductResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryUpdateProduct",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryUpdateProductRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryUpdateProductResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryRemoveProduct",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryRemoveProductRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryRemoveProductResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCurrentStore",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCurrentStoreRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCurrentStoreResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductSetSpecialPrice",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductSetSpecialPriceRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductSetSpecialPriceResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductGetSpecialPrice",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductGetSpecialPriceRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductGetSpecialPriceResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductDelete",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDeleteRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDeleteResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeCurrentStore",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeCurrentStoreRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeCurrentStoreResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeOptions",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeOptionsRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeOptionsResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionTypes",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionTypesRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionTypesResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionValueList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionValueInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionValueAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionValueUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductCustomOptionValueRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductCustomOptionValueRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetAttributeAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetAttributeAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetAttributeAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetAttributeRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetAttributeRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetAttributeRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetGroupAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetGroupAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetGroupAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetGroupRename",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetGroupRenameRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetGroupRenameResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeSetGroupRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetGroupRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeSetGroupRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductTypeList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTypeListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTypeListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeTierPriceInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeTierPriceInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeTierPriceInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeTierPriceUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeTierPriceUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeTierPriceUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryAttributeCurrentStore",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAttributeCurrentStoreRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAttributeCurrentStoreResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryAttributeList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAttributeListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAttributeListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogCategoryAttributeOptions",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAttributeOptionsRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogCategoryAttributeOptionsResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaCurrentStore",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaCurrentStoreRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaCurrentStoreResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaTypes",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaTypesRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaTypesResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeMediaRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeMediaRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductLinkList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductLinkAssign",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkAssignRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkAssignResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductLinkUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductLinkRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductLinkTypes",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkTypesRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkTypesResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductLinkAttributes",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkAttributesRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductLinkAttributesResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductAttributeCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductAttributeCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderAddComment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderAddCommentRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderAddCommentResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderHold",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderHoldRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderHoldResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderUnhold",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderUnholdRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderUnholdResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderCancel",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCancelRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCancelResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentAddComment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentAddCommentRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentAddCommentResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentAddTrack",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentAddTrackRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentAddTrackResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentRemoveTrack",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentRemoveTrackRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentRemoveTrackResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentSendInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentSendInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentSendInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderShipmentGetCarriers",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentGetCarriersRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderShipmentGetCarriersResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceAddComment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceAddCommentRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceAddCommentResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceCapture",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceCaptureRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceCaptureResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceVoid",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceVoidRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceVoidResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderInvoiceCancel",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceCancelRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderInvoiceCancelResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderCreditmemoList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderCreditmemoInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderCreditmemoCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderCreditmemoAddComment",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoAddCommentRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoAddCommentResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "salesOrderCreditmemoCancel",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoCancelRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "salesOrderCreditmemoCancelResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogInventoryStockItemList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogInventoryStockItemListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogInventoryStockItemListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogInventoryStockItemUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogInventoryStockItemUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogInventoryStockItemUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartTotals",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartTotalsRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartTotalsResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartOrder",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartOrderRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartOrderResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartLicense",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartLicenseRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartLicenseResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartProductAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartProductUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartProductRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartProductList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartProductMoveToCustomerQuote",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductMoveToCustomerQuoteRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartProductMoveToCustomerQuoteResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCustomerSet",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerSetRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerSetResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCustomerAddresses",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerAddressesRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerAddressesResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartShippingMethod",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartShippingMethodRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartShippingMethodResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartShippingList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartShippingListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartShippingListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartPaymentMethod",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartPaymentMethodRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartPaymentMethodResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartPaymentList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartPaymentListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartPaymentListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCouponAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCouponAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCouponAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCouponRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCouponRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCouponRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductTagList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductTagInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductTagAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductTagUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductTagRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductTagRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftMessageSetForQuote",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftMessageForQuoteRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftMessageForQuoteResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftMessageSetForQuoteItem",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftMessageForQuoteItemRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftMessageForQuoteItemResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftMessageSetForQuoteProduct",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftMessageForQuoteProductRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftMessageForQuoteProductResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductDownloadableLinkAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDownloadableLinkAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDownloadableLinkAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductDownloadableLinkList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDownloadableLinkListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDownloadableLinkListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "catalogProductDownloadableLinkRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDownloadableLinkRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "catalogProductDownloadableLinkRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "enterpriseCustomerbalanceBalance",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "enterpriseCustomerbalanceBalanceRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "enterpriseCustomerbalanceBalanceResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "enterpriseCustomerbalanceHistory",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "enterpriseCustomerbalanceHistoryRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "enterpriseCustomerbalanceHistoryResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCustomerbalanceSetAmount",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerbalanceSetAmountRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerbalanceSetAmountResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartCustomerbalanceRemoveAmount",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerbalanceRemoveAmountRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartCustomerbalanceRemoveAmountResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardAccountCreate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountCreateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountCreateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardAccountUpdate",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountUpdateRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountUpdateResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardAccountRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardAccountList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardAccountInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardAccountInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardCustomerInfo",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardCustomerInfoRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardCustomerInfoResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "giftcardCustomerRedeem",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardCustomerRedeemRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "giftcardCustomerRedeemResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartGiftcardAdd",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartGiftcardAddRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartGiftcardAddResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartGiftcardRemove",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartGiftcardRemoveRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartGiftcardRemoveResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "",
      "shoppingCartGiftcardList",
      [ [:in, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartGiftcardListRequestParam"]],
        [:out, "parameters", ["::SOAP::SOAPElement", "urn:Magento", "shoppingCartGiftcardListResponseParam"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = MagentoMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = MagentoMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

